name: Docker

on:
  workflow_call:
  
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: program
          

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: arkhandyr
        password: ${{ secrets.PASSWORD_DOCKERHUB }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.1.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: Arkhandyr/ci_cd_tests:${{github.ref_name}}
            
